== Title IX
 
Bryn Mawr/Haverford College is committed to fostering a safe and inclusive
living and learning environment where all can feel secure and free from
harassment. All forms of sexual misconduct, including sexual assault, sexual
harassment, stalking, domestic violence, and dating violence are violations of
Bryn Mawr/Haverford's policies, whether they occur on or off campus. Bryn
Mawr/Haverford faculty are committed to helping to create a safe learning
environment for all students and for the College community as a whole. If you
have experienced any form of gender or sex-based discrimination, harassment, or
violence, know that help and support are available. Staff members are trained
to support students in navigating campus life, accessing health and counseling
services, providing academic and housing accommodations, and more.  
 
The College strongly encourages all students to report any incidents of sexual
misconduct. Please be aware that all Bryn Mawr/Haverford employees (other than
those designated as confidential resources such as counselors, clergy, and
healthcare providers) are required to report information about such
discrimination and harassment to the
link:https://www.haverford.edu/users/ktaylor4[Bi-College Title IX Coordinator].  
 
Information about the College's Sexual Misconduct policy, reporting options,
and a list of campus and local resources can be found on the College's
website: 
 
link:https://www.brynmawr.edu/titleix[Bryn Mawr Sexual Misconduct Policy]
 
link:https://www.haverford.edu/sexual-misconduct[Haverford Sexual Misconduct Policy]

